graphs:
	go run graph.go

remove-graphs:
	rm *.png

create-example-config:
	echo '{' > config.json && \
	echo '  "trajectory_csv": "",' >> config.json && \
	echo '  "waypoints_csv": "",' >> config.json && \
	echo '  "arm_kinematics_path": ""' >> config.json && \
	echo '}' >> config.json
