viam-camera-realsense:
  image_arm64: ghcr.io/viamrobotics/viam-camera-realsense:arm64
  image_amd64: ghcr.io/viamrobotics/viam-camera-realsense:amd64
  minimum_date: 2023-08-15T03:54:00.0Z
  persistent: true