# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /host

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /host

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /host/CMakeFiles /host//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /host/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named universal-robots

# Build rule for target.
universal-robots: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 universal-robots
.PHONY : universal-robots

# fast build rule for target.
universal-robots/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/universal-robots.dir/build.make CMakeFiles/universal-robots.dir/build
.PHONY : universal-robots/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/universal-robots.dir/build.make CMakeFiles/universal-robots.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/universal-robots.dir/build.make CMakeFiles/universal-robots.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/universal-robots.dir/build.make CMakeFiles/universal-robots.dir/main.cpp.s
.PHONY : main.cpp.s

src/UR5e-Arm.o: src/UR5e-Arm.cpp.o
.PHONY : src/UR5e-Arm.o

# target to build an object file
src/UR5e-Arm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/universal-robots.dir/build.make CMakeFiles/universal-robots.dir/src/UR5e-Arm.cpp.o
.PHONY : src/UR5e-Arm.cpp.o

src/UR5e-Arm.i: src/UR5e-Arm.cpp.i
.PHONY : src/UR5e-Arm.i

# target to preprocess a source file
src/UR5e-Arm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/universal-robots.dir/build.make CMakeFiles/universal-robots.dir/src/UR5e-Arm.cpp.i
.PHONY : src/UR5e-Arm.cpp.i

src/UR5e-Arm.s: src/UR5e-Arm.cpp.s
.PHONY : src/UR5e-Arm.s

# target to generate assembly for a file
src/UR5e-Arm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/universal-robots.dir/build.make CMakeFiles/universal-robots.dir/src/UR5e-Arm.cpp.s
.PHONY : src/UR5e-Arm.cpp.s

trajectories/Path.o: trajectories/Path.cpp.o
.PHONY : trajectories/Path.o

# target to build an object file
trajectories/Path.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/universal-robots.dir/build.make CMakeFiles/universal-robots.dir/trajectories/Path.cpp.o
.PHONY : trajectories/Path.cpp.o

trajectories/Path.i: trajectories/Path.cpp.i
.PHONY : trajectories/Path.i

# target to preprocess a source file
trajectories/Path.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/universal-robots.dir/build.make CMakeFiles/universal-robots.dir/trajectories/Path.cpp.i
.PHONY : trajectories/Path.cpp.i

trajectories/Path.s: trajectories/Path.cpp.s
.PHONY : trajectories/Path.s

# target to generate assembly for a file
trajectories/Path.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/universal-robots.dir/build.make CMakeFiles/universal-robots.dir/trajectories/Path.cpp.s
.PHONY : trajectories/Path.cpp.s

trajectories/Trajectory.o: trajectories/Trajectory.cpp.o
.PHONY : trajectories/Trajectory.o

# target to build an object file
trajectories/Trajectory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/universal-robots.dir/build.make CMakeFiles/universal-robots.dir/trajectories/Trajectory.cpp.o
.PHONY : trajectories/Trajectory.cpp.o

trajectories/Trajectory.i: trajectories/Trajectory.cpp.i
.PHONY : trajectories/Trajectory.i

# target to preprocess a source file
trajectories/Trajectory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/universal-robots.dir/build.make CMakeFiles/universal-robots.dir/trajectories/Trajectory.cpp.i
.PHONY : trajectories/Trajectory.cpp.i

trajectories/Trajectory.s: trajectories/Trajectory.cpp.s
.PHONY : trajectories/Trajectory.s

# target to generate assembly for a file
trajectories/Trajectory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/universal-robots.dir/build.make CMakeFiles/universal-robots.dir/trajectories/Trajectory.cpp.s
.PHONY : trajectories/Trajectory.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... universal-robots"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/UR5e-Arm.o"
	@echo "... src/UR5e-Arm.i"
	@echo "... src/UR5e-Arm.s"
	@echo "... trajectories/Path.o"
	@echo "... trajectories/Path.i"
	@echo "... trajectories/Path.s"
	@echo "... trajectories/Trajectory.o"
	@echo "... trajectories/Trajectory.i"
	@echo "... trajectories/Trajectory.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

