#include "dh_kinematics.hpp"

#include <cmath>
#include <map>
#include <optional>
#include <stdexcept>
#include <string>
#include <variant>

#include <json/json.h>

namespace viam_ur {

namespace {

constexpr double k_rad_to_deg = 180.0 / M_PI;
constexpr double k_m_to_mm = 1000.0;

struct JointLimits {
    double min_deg;
    double max_deg;
};

// A capsule geometry expressed in the DH static-link local frame.
// All translations in millimeters; orientation as a unit quaternion (W, X, Y, Z).
struct CapsuleGeometry {
    double radius_mm;
    double length_mm;
    double tx_mm;
    double ty_mm;
    double tz_mm;
    double qw;
    double qx;
    double qy;
    double qz;
};

// A sphere geometry expressed in the DH static-link local frame.
struct SphereGeometry {
    double radius_mm;
    double tx_mm;
    double ty_mm;
    double tz_mm;
};

using Geometry = std::variant<CapsuleGeometry, SphereGeometry>;

struct ModelTables {
    std::array<JointLimits, 6> limits;
    // One optional geometry per DH entry. nullopt means "no geometry on this segment".
    std::array<std::optional<Geometry>, 6> geometries;
};

// Per-model static tables. To register a new UR model, add an entry here.
const std::map<std::string, ModelTables>& model_tables() {
    static const std::map<std::string, ModelTables> tables = [] {
        std::map<std::string, ModelTables> t;

        // ur20: limits taken from existing kinematics/ur20.json (verified in spec).
        ModelTables ur20;
        ur20.limits = {{
            {-360.0, 360.0},  // shoulder_pan
            {-360.0, 360.0},  // shoulder_lift
            {-180.0, 180.0},  // elbow
            {-360.0, 360.0},  // wrist_1
            {-360.0, 360.0},  // wrist_2
            {-360.0, 360.0},  // wrist_3
        }};
        // Generated by tools/derive_dh_capsules.py -- do not edit by hand.
        ur20.geometries[0] = CapsuleGeometry{
            /* radius_mm */ 122.5,
            /* length_mm */ 333,
            /* tx_mm */ 0.0,
            /* ty_mm */ 0.0,
            /* tz_mm */ 136.3,
            /* qw */ 0.0,
            /* qx */ 0.0,
            /* qy */ 0.0,
            /* qz */ 1.0,
        };  // shoulder_link
        ur20.geometries[1] = CapsuleGeometry{
            /* radius_mm */ 90,
            /* length_mm */ 1032,
            /* tx_mm */ -421.600000,
            /* ty_mm */ -0.000000,
            /* tz_mm */ 260.000000,
            /* qw */ -0.500000000,
            /* qx */ -0.500000000,
            /* qy */ 0.500000000,
            /* qz */ 0.500000000,
        };  // upper_arm_link
        ur20.geometries[2] = CapsuleGeometry{
            /* radius_mm */ 75,
            /* length_mm */ 858,
            /* tx_mm */ -360.0,
            /* ty_mm */ 0.0,
            /* tz_mm */ 43.0,
            /* qw */ -0.5,
            /* qx */ -0.5,
            /* qy */ 0.5,
            /* qz */ 0.5,
        };  // forearm_link
        ur20.geometries[3] = CapsuleGeometry{
            /* radius_mm */ 48.5,
            /* length_mm */ 262,
            /* tx_mm */ 0.0,
            /* ty_mm */ 0.0,
            /* tz_mm */ 123.5,
            /* qw */ 1.0,
            /* qx */ 0.0,
            /* qy */ 0.0,
            /* qz */ 0.0,
        };  // wrist_1_link
        ur20.geometries[4] = CapsuleGeometry{
            /* radius_mm */ 48.5,
            /* length_mm */ 260,
            /* tx_mm */ 0.0,
            /* ty_mm */ 0.0,
            /* tz_mm */ 84.4,
            /* qw */ 1.0,
            /* qx */ 0.0,
            /* qy */ 0.0,
            /* qz */ 0.0,
        };  // wrist_2_link
        ur20.geometries[5] = CapsuleGeometry{
            /* radius_mm */ 48.5,
            /* length_mm */ 204,
            /* tx_mm */ 0.0,
            /* ty_mm */ 0.0,
            /* tz_mm */ 85.0,
            /* qw */ 1.0,
            /* qx */ 0.0,
            /* qy */ 0.0,
            /* qz */ 0.0,
        };  // wrist_3_link
        t.emplace("ur20", std::move(ur20));

        // ur5e: limits taken from existing kinematics/ur5e.json. Geometries are
        // initial best-guess values translated from the SVA blocks in ur5e.json
        // using the same `tz = SVA_z + d[i]` pattern that worked for ur20 plus
        // the ur5e nominal d values; expect to tune empirically against the arm.
        // Calibrated a/d/alpha will be substituted in at runtime from KinematicsInfo.
        ModelTables ur5e;
        ur5e.limits = {{
            {-360.0, 360.0},  // shoulder_pan
            {-360.0, 360.0},  // shoulder_lift
            {-180.0, 180.0},  // elbow
            {-360.0, 360.0},  // wrist_1
            {-360.0, 360.0},  // wrist_2
            {-360.0, 360.0},  // wrist_3
        }};
        // shoulder_link in ur5e.json is a sphere (r=55, no length, no translation).
        // Place at the DH static-link origin shifted by d[0]=162.5 along z (same
        // pattern as the ur20 shoulder).
        ur5e.geometries[0] = SphereGeometry{
            /* radius_mm */ 55.0,
            /* tx_mm */ 0.0,
            /* ty_mm */ 0.0,
            /* tz_mm */ 162.5,
        };  // shoulder_link
        // upper_arm_link: capsule r=65, l=550, SVA local (-212.5, -130, 0).
        // d[1]=0 so no z-shift; orientation matches the ur20 upper_arm pattern.
        ur5e.geometries[1] = CapsuleGeometry{
            /* radius_mm */ 65.0,
            /* length_mm */ 550.0,
            /* tx_mm */ -212.5,
            /* ty_mm */ -130.0,
            /* tz_mm */ 0.0,
            /* qw */ -0.5,
            /* qx */ -0.5,
            /* qy */ 0.5,
            /* qz */ 0.5,
        };  // upper_arm_link
        // forearm_link: capsule r=50, l=490, SVA local (-196.1, 0, 0). d[2]=0.
        ur5e.geometries[2] = CapsuleGeometry{
            /* radius_mm */ 50.0,
            /* length_mm */ 490.0,
            /* tx_mm */ -196.1,
            /* ty_mm */ 0.0,
            /* tz_mm */ 0.0,
            /* qw */ -0.5,
            /* qx */ -0.5,
            /* qy */ 0.5,
            /* qz */ 0.5,
        };  // forearm_link
        // wrist_1_link: capsule r=40, l=230, SVA local (0, -80.65, 0).
        // d[3]=133.3; tz = -80.65 + 133.3 = 52.65 by the ur20-shoulder pattern.
        ur5e.geometries[3] = CapsuleGeometry{
            /* radius_mm */ 40.0,
            /* length_mm */ 230.0,
            /* tx_mm */ 0.0,
            /* ty_mm */ 0.0,
            /* tz_mm */ 52.65,
            /* qw */ 1.0,
            /* qx */ 0.0,
            /* qy */ 0.0,
            /* qz */ 0.0,
        };  // wrist_1_link
        // wrist_2_link in ur5e.json is a sphere (r=70, no length).
        // Same shift pattern: tz = 0 + d[4] = 99.7.
        ur5e.geometries[4] = SphereGeometry{
            /* radius_mm */ 70.0,
            /* tx_mm */ 0.0,
            /* ty_mm */ 0.0,
            /* tz_mm */ 99.7,
        };  // wrist_2_link
        // ee_link (the "wrist_3" capsule in ur5e.json): r=40, l=170, SVA local
        // (0, -49.85, 0). d[5]=99.6; tz = -49.85 + 99.6 = 49.75.
        ur5e.geometries[5] = CapsuleGeometry{
            /* radius_mm */ 40.0,
            /* length_mm */ 170.0,
            /* tx_mm */ 0.0,
            /* ty_mm */ 0.0,
            /* tz_mm */ 49.75,
            /* qw */ 1.0,
            /* qx */ 0.0,
            /* qy */ 0.0,
            /* qz */ 0.0,
        };  // ee_link / wrist_3
        t.emplace("ur5e", std::move(ur5e));

        return t;
    }();
    return tables;
}

Json::Value capsule_to_json(const CapsuleGeometry& c) {
    Json::Value g(Json::objectValue);
    g["type"] = "capsule";
    g["r"] = c.radius_mm;
    g["l"] = c.length_mm;

    Json::Value translation(Json::objectValue);
    translation["x"] = c.tx_mm;
    translation["y"] = c.ty_mm;
    translation["z"] = c.tz_mm;
    g["translation"] = translation;

    Json::Value orient(Json::objectValue);
    orient["type"] = "quaternion";
    Json::Value qval(Json::objectValue);
    qval["W"] = c.qw;
    qval["X"] = c.qx;
    qval["Y"] = c.qy;
    qval["Z"] = c.qz;
    orient["value"] = qval;
    g["orientation"] = orient;

    return g;
}

Json::Value sphere_to_json(const SphereGeometry& s) {
    Json::Value g(Json::objectValue);
    g["type"] = "sphere";
    g["r"] = s.radius_mm;

    Json::Value translation(Json::objectValue);
    translation["x"] = s.tx_mm;
    translation["y"] = s.ty_mm;
    translation["z"] = s.tz_mm;
    g["translation"] = translation;

    return g;
}

Json::Value geometry_to_json(const Geometry& geom) {
    return std::visit(
        [](const auto& g) -> Json::Value {
            using T = std::decay_t<decltype(g)>;
            if constexpr (std::is_same_v<T, CapsuleGeometry>) {
                return capsule_to_json(g);
            } else {
                return sphere_to_json(g);
            }
        },
        geom);
}

}  // namespace

std::string build_dh_kinematics_json(const std::string& model_name, const DHParams6& dh) {
    const auto& tables = model_tables();
    const auto it = tables.find(model_name);
    if (it == tables.end()) {
        throw std::invalid_argument("build_dh_kinematics_json: no per-model table for `" + model_name + "`");
    }
    const ModelTables& tbl = it->second;

    Json::Value root(Json::objectValue);
    root["name"] = model_name;
    root["kinematic_param_type"] = "SVA";

    Json::Value joints(Json::arrayValue);
    Json::Value links(Json::arrayValue);

    for (size_t i = 0; i < 6; ++i) {
        const std::string joint_id = model_name + "_q_" + std::to_string(i);
        const std::string link_id = model_name + "_link_" + std::to_string(i);
        const std::string joint_parent = (i == 0) ? std::string{"world"} : (model_name + "_link_" + std::to_string(i - 1));

        // Revolute joint around Z. Limits in degrees per the per-model table.
        Json::Value joint(Json::objectValue);
        joint["id"] = joint_id;
        joint["type"] = "revolute";
        joint["parent"] = joint_parent;
        Json::Value axis(Json::objectValue);
        axis["x"] = 0.0;
        axis["y"] = 0.0;
        axis["z"] = 1.0;
        joint["axis"] = axis;
        joint["min"] = tbl.limits[i].min_deg;
        joint["max"] = tbl.limits[i].max_deg;
        joints.append(joint);

        // Static link pose = Rz(theta_i) * T(a_i, 0, d_i) * Rx(alpha_i).
        // Composed:
        //   translation = Rz(theta) * (a, 0, d) = (a*cos(theta), a*sin(theta), d)
        //   rotation    = Rz(theta) * Rx(alpha)
        const double theta_i = dh.theta[i];
        const double alpha_i = dh.alpha[i];
        const double a_mm = dh.a[i] * k_m_to_mm;
        const double d_mm = dh.d[i] * k_m_to_mm;

        const double ct = std::cos(theta_i);
        const double st = std::sin(theta_i);
        Json::Value translation(Json::objectValue);
        translation["x"] = a_mm * ct;
        translation["y"] = a_mm * st;
        translation["z"] = d_mm;

        // Quaternion for Rz(theta) * Rx(alpha):
        //   qZ = (cos(theta/2), 0, 0, sin(theta/2))
        //   qX = (cos(alpha/2), sin(alpha/2), 0, 0)
        //   qZ * qX = (cz*cx, cz*sx, sz*sx, sz*cx)
        const double cz = std::cos(theta_i / 2.0);
        const double sz = std::sin(theta_i / 2.0);
        const double cx = std::cos(alpha_i / 2.0);
        const double sx = std::sin(alpha_i / 2.0);
        Json::Value orient(Json::objectValue);
        orient["type"] = "quaternion";
        Json::Value qval(Json::objectValue);
        qval["W"] = cz * cx;
        qval["X"] = cz * sx;
        qval["Y"] = sz * sx;
        qval["Z"] = sz * cx;
        orient["value"] = qval;

        Json::Value link(Json::objectValue);
        link["id"] = link_id;
        link["parent"] = joint_id;
        link["translation"] = translation;
        link["orientation"] = orient;
        if (tbl.geometries[i].has_value()) {
            link["geometry"] = geometry_to_json(*tbl.geometries[i]);
        }
        links.append(link);
    }

    root["joints"] = joints;
    root["links"] = links;

    Json::StreamWriterBuilder writer;
    writer["indentation"] = "    ";
    return Json::writeString(writer, root);
}

}  // namespace viam_ur
